spring:
  application:
    name: adventure-pomodoro
  data:
    mongodb:
      database: adventurepom

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/adventure-pomodoro     			   
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com